### ISSUE TITLE
Update version of R8 to latest

### ISSUE THREAD

**Issue by jstewart5000** [slackhq/keeper#125]
**Keeper version:** `0.15.0`

_keeper_ currently uses a version of R8 that breaks when attempting to bump our JVM Target to `17` (currently at `11`) 

#### Steps to reproduce:

1. Update JVM target version to `17`
2. Attempt to assemble one of the artifacts that depend on _keeper_ 
> (ex. `:app:inferInternalReleaseAndroidTestKeepRulesForKeeper`

#### Expected result:
Task completes ✅ and _keeper_ related tasks are successfully ran

#### Actual result:
```
java.lang.IllegalArgumentException: Unsupported class file major version 61	
Compilation failed with an internal error.	
com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at Version.fakeStackEntry(Version_3.0.9-dev.java:0)	
	at com.android.tools.r8.utils.ExceptionUtils.failWithFakeEntry(ExceptionUtils.java:130)	
	at com.android.tools.r8.utils.ExceptionUtils.failCompilation(ExceptionUtils.java:80)	
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:74)	
	at com.android.tools.r8.tracereferences.TraceReferences.run(TraceReferences.java:30)	
	at com.android.tools.r8.tracereferences.TraceReferences.run(TraceReferences.java:84)	
	at com.android.tools.r8.tracereferences.TraceReferences.lambda$main$2(TraceReferences.java:98)	
	at com.android.tools.r8.utils.ExceptionUtils.withMainProgramHandler(ExceptionUtils.java:177)	
	at com.android.tools.r8.tracereferences.TraceReferences.main(TraceReferences.java:98)	
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61

```

#### Attachments:

Logs attached
[emdqxxpw5ibiy-console-log.txt](https://github.com/slackhq/keeper/files/12771954/emdqxxpw5ibiy-console-log.txt)

**Comment by jstewart5000** [comment]
- [R8 Version](https://github.com/slackhq/keeper/blob/main/keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperPlugin.kt#L95) Currently: `3.2.78`
- https://github.com/slackhq/keeper/blob/1dc49abf458fcf7854e28c7d019500035d218177/docs/configuration.md#custom-r8-behavior

**Comment by ZacSweers** [comment]
Figured this one out, not a Keeper issue. We can update the default version to the latest AGP stable though
