### ISSUE TITLE
PrintUses fails with AssertionError with kotlin 1.3.70

### ISSUE THREAD

**Issue by dsvoronin** [slackhq/keeper#31]
**Keeper version:** 0.2.0

#### Steps to reproduce:

1. bump kotlin version to 1.3.70 
2. run app:infer<testBuildType>TestUsageForKeeper

reproduced in avito-tech/avito-android/pull/238

#### Expected result:

All is ok, like with kotlin 1.3.61

#### Actual result:

```
java.lang.AssertionError: Could not find method Method kotlin.reflect.KClasses.getDefaultType Proto LL kotlin.reflect.KType kotlin.reflect.KClass
        at com.android.tools.r8.PrintUses$UseCollector.addMethod(PrintUses.java:224)
        at com.android.tools.r8.PrintUses$UseCollector.registerInvokeStatic(PrintUses.java:117)
        at com.android.tools.r8.cf.code.CfInvoke.registerUse(CfInvoke.java:103)
        at com.android.tools.r8.graph.CfCode.registerCodeReferences(CfCode.java:380)
        at com.android.tools.r8.graph.LazyCfCode.registerCodeReferences(LazyCfCode.java:224)
        at com.android.tools.r8.graph.DexEncodedMethod.registerCodeReferences(DexEncodedMethod.java:1234)
        at com.android.tools.r8.PrintUses$UseCollector.registerMethod(PrintUses.java:259)
        at com.android.tools.r8.PrintUses$UseCollector.access$1300(PrintUses.java:80)
        at com.android.tools.r8.PrintUses.lambda$analyze$0(PrintUses.java:361)
        at com.android.tools.r8.graph.DexClass.forEachMethod(DexClass.java:346)
        at com.android.tools.r8.PrintUses.analyze(PrintUses.java:361)
        at com.android.tools.r8.PrintUses.main(PrintUses.java:329)
```

#### Attachments:

Created as issue in google tracker (r8 component) https://issuetracker.google.com/issues/151002499

**Comment by ZacSweers** [comment]
Looks like you've gotten an explanation in the R8 tool. Let's continue the discussion in there since it looks like it's revealing a legitimate issue in your dependencies 👍.

For what it's worth - we updated to 1.3.70 internally and haven't had any issues.
