### ISSUE TITLE
Execution failed for task ':inferBuildVariantAndroidTestKeepRulesForKeeper'

### ISSUE THREAD

**Issue by vsocfit** [slackhq/keeper#56]
**Keeper version:** _0.6.0_

Using 0.6.0 infer rules task failes:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':inferBuildVariantAndroidTestKeepRulesForKeeper'.

#### Steps to reproduce:

**AGP:** _4.0.0_
**Gradle:** _6.5_

#### Expected result:

Build successful

#### Actual result:

Gradle build failed:
![image](https://user-images.githubusercontent.com/61582907/85010490-c3ec9b80-b168-11ea-93b0-e2a388c75a5e.png)

**Comment by vsocfit** [comment]
> Task :inferBuildVariantAndroidTestKeepRulesForKeeper
Exception in thread "main" java.lang.AssertionError
 at com.android.tools.r8.PrintUses$UseCollector.addMethod(PrintUses.java:211)
 at com.android.tools.r8.PrintUses$UseCollector.registerInvokeStatic(PrintUses.java:108)
 at com.android.tools.r8.cf.code.CfInvoke.registerUse(CfInvoke.java:101)
 at com.android.tools.r8.graph.CfCode.registerCodeReferences(CfCode.java:376)
 at com.android.tools.r8.graph.LazyCfCode.registerCodeReferences(LazyCfCode.java:204)
 at com.android.tools.r8.graph.DexEncodedMethod.registerCodeReferences(DexEncodedMethod.java:1070)
 at com.android.tools.r8.PrintUses$UseCollector.registerMethod(PrintUses.java:240)
 at com.android.tools.r8.PrintUses$UseCollector.access$1200(PrintUses.java:77)
 at com.android.tools.r8.PrintUses.lambda$analyze$0(PrintUses.java:340)
 at com.android.tools.r8.graph.DexClass.forEachMethod(DexClass.java:297)
 at com.android.tools.r8.PrintUses.analyze(PrintUses.java:340)
 at com.android.tools.r8.PrintUses.main(PrintUses.java:309)

**Comment by ZacSweers** [comment]
Can you give more details or a reproducible sample? You can disable assertions via the keeper extension and R8 will print errors to the generated rules file instead

**Comment by vsocfit** [comment]
Currently I'm looking on https://github.com/slackhq/keeper/issues/31 as it seems to have had a similar issue. Will come back with more info.

**Comment by ZacSweers** [comment]
@vsocfit any luck?

**Comment by ZacSweers** [comment]
Closing this out for now, feel free to circle back if you have any more info!
