### ISSUE TITLE
Add better troubleshooting docs for PrintUses assertion errors

### ISSUE THREAD

**Issue by ZacSweers** [slackhq/keeper#66]
These aren't very obvious to consumers. Can we improve this?

Ideas:
* Ask folks to try this in the issue template
* Try/catch the exec and catch assertion issues? Maybe retry with them disabled or print verbose logging to try with assertions disabled and investigate the generated proguard file (with its output location)

**Comment by pgreze** [comment]
Maybe use a more recent version of R8 could be helpful.

For example for the problem I shared few days ago the stacktrace with the version 1.6.53 was:

```
Exception in thread "main" java.lang.AssertionError
	at com.android.tools.r8.PrintUses$UseCollector.addMethod(PrintUses.java:211)
	at com.android.tools.r8.PrintUses$UseCollector.registerInvokeStatic(PrintUses.java:108)
	at com.android.tools.r8.cf.code.CfInvoke.registerUse(CfInvoke.java:101)
```

But by using the more recent version 2.2.40:

```
Exception in thread "main" java.lang.AssertionError: Could not find method Method com.google.common.base.Strings.lenientFormat Proto LLL java.lang.String java.lang.String java.lang.Object[]
	at com.android.tools.r8.PrintUses$UseCollector.addMethod(PrintUses.java:234)
	at com.android.tools.r8.PrintUses$UseCollector.registerInvokeStatic(PrintUses.java:129)
	at com.android.tools.r8.graph.UseRegistry.registerInvokeStatic(UseRegistry.java:49)
...
```

**Comment by ZacSweers** [comment]
We'll want to raise it once the new tracereferences CLI is available (hopefully soon)

**Comment by ZacSweers** [comment]
You can also manually try with newer versions locally. See https://github.com/Kotlin/kotlinx.coroutines/pull/1923

**Comment by pgreze** [comment]
@ZacSweers you're right.
I was wondering if it's complicated to bump the version that keeper is using by default (1.6.53 was released in November 2019). After all it's using its own configuration to fetch the dependency, so we could bring latest versions improvements for free. What do you think?

**Comment by ZacSweers** [comment]
Answered above already - we'll raise it when tracereferences is available. We could consider updating sooner if there's a confirmed bugfix in a newer version, but so far there's been no such case. Let's keep this issue focused on the original topic of making failures more actionable.

**Comment by ZacSweers** [comment]
Going to close this for now as it seems not worth trying to invest further in this
