### ISSUE TITLE
Some desugared java.time classes are not kept

### ISSUE THREAD

**Issue by markrietveld** [slackhq/keeper#67]
**Keeper version:** 0.7.0

Usages of `DateTimeFormatterBuilder` (and perhaps others) in the main app when run from tests can lead to exceptions when minified. These exceptions don't happen when the minified app is run directly, and also don't happen when tests are run without minification.

#### Steps to reproduce:

1. Add this instance variable to `SampleApplication` app:
```
DateTimeFormatter formatter = new DateTimeFormatterBuilder()
    .parseCaseInsensitive()
    .appendInstant(9)
    .toFormatter()
    .withResolverStyle(ResolverStyle.STRICT);
```

2. Run tests

#### Expected result:

Tests pass

#### Actual result:

Tests fail with exceptions

#### Attachments:
Logs from Keeper sample app with `DateTimeFormatterBuilder` added,

```
java.lang.RuntimeException: Unable to instantiate application com.slack.keeper.sample.SampleApplication: java.lang.ClassCastException: j$.time.format.ResolverStyle[] cannot be cast to j$.time.format.ResolverStyle
        at android.app.LoadedApk.makeApplication(LoadedApk.java:578)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassCastException: j$.time.format.ResolverStyle[] cannot be cast to j$.time.format.ResolverStyle
        at j$.time.format.DateTimeFormatter.<init>(:1380)
        at j$.time.format.DateTimeFormatter.withResolverStyle(:1591)
        at com.slack.keeper.sample.SampleApplication.<init>(:39)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newApplication(Instrumentation.java:996)
        at android.app.Instrumentation.newApplication(Instrumentation.java:981)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680) 
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

We also see this stack trace in our app with that exact `DateTimeFormatterBuilder` snippet:

```
Caused by: java.lang.IllegalStateException: Cannot call optionalEnd() as there was no previous call to optionalStart()
	at j$.time.format.DateTimeFormatterBuilder.optionalEnd(DateTimeFormatterBuilder.java:1987)
	at redacted.<clinit>(SourceFile:37)
	... 26 more
```

**Comment by ZacSweers** [comment]
Thanks! Will take a look 👀

**Comment by wzieba** [comment]
+1, in my case those are not kept:
- `java.time.Clock#systemDefaultZone`
- `java.time.Duratiton#ofMinutets`

In my case, it happens _sometimes_ - almost always when running a build with `--rerun-tasks`. I can't provide a reproduction sample though, as it only happens on an internal codebase 😞.

**Comment by ZacSweers** [comment]
I was able to reproduce with Mark's example, I just haven't had a chance to look into it more yet

**Comment by ZacSweers** [comment]
FWIW I'm still stuck here. We actually are at an impasse internally with library desugaring because it appears to package a dedicated dex file in each APK, which then have different implementations and conflict at runtime. I suspect this is related to that issue.

**Comment by ZacSweers** [comment]
Finally got this working https://github.com/slackhq/keeper/pull/84
