### ISSUE TITLE
Keeper throw AssertionError because of excluded dependency

### ISSUE THREAD

**Issue by dimkinware** [slackhq/keeper#95]
Hello,

I have the problem:

1. I have to exclude `protobuf-lite` dependency from the `espresso:espresso-contrib` library because it leads to crash due to conflict with java-protobuf-lite from other libraries

```
configurations {
    androidTestImplementation {
        exclude group: "com.google.protobuf", module: "protobuf-lite"
    }
}
```

2. If I do that the Keeper plugin throw the error during `inferGooglePlayReleaseAndroidTestKeepRulesForKeeper` task:
```
Exception in thread "main" java.lang.AssertionError: com.google.protobuf.GeneratedMessageLite$MethodToInvoke com.google.protobuf.GeneratedMessageLite$MethodToInvoke.IS_INITIALIZED
	at com.android.tools.r8.PrintUses$UseCollector.addField(PrintUses.java:213)
	at com.android.tools.r8.PrintUses$UseCollector.registerStaticFieldRead(PrintUses.java:165)
	at com.android.tools.r8.cf.code.CfFieldInstruction.internalRegisterUse(CfFieldInstruction.java:107)

```
 
How can I say Keeper to ignore processing `protobuf-lite` dependency? Or maybe there is another workaround?

Thank you!

**Comment by ZacSweers** [comment]
That's coming from R8, not keeper. Please file an issue over on Google's issue tracker with repro steps. Alternatively, you can try the new tracereferences tool.
